name: Deploy to Next.js
on:
    push:
        branches:
            - main #zmień na nazwę swojego brancha, na którym chcesz, aby zmiany powodowały przebudowanie
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies and build
              run: |
                  npm install
                  npm run build
